### ISSUE TITLE
Desplegar BOT en cloud

### ISSUE THREAD

**Issue by BorjaC** [BorjaC/TMI_G01#26]
Se debe desplegar el bot en la nube de Google, y asegurar la conexión desde los clientes de telegram. 

El resultado de la issue debe ser una wiki explicando paso por paso la realización del proceso. _Se agradece acompañar la wiki con alguna imagen/esquema ilustrativo del proceso de despliegue y el proceso de comunicación_

**Comment by CFjavi** [comment]
Por problemas de incompatibilidad entre el tipo de proyecto generado y el requerido para desplegar la aplicación en Google Cloud, no se pudo completar.
