### ISSUE TITLE
Herramienta de análisis de imagen

### ISSUE THREAD

**Issue by BorjaC** [BorjaC/TMI_G01#28]
Se debe desarrollar una herramienta de análisis de la imagen. Para ello, se pide que la herramienta reciba una imagen y a partir de la misma sea capaz de predecir si ha sido manipulada o no. 

La herramienta tiene que estar totalmente desvinculada de la API, por ello se permite la creación de la misma en cualquier lenguaje.

El resultado de la issue debe ser la herramienta alojada en el repositorio correspondiente.

**Comment by SantiagoDuque** [comment]
Tareas:

- investigar relacion de los pixeles en un imagen
- generar algoritmo que los interprete
- crear herramienta
